# Generated by Django 3.0.8 on 2020-07-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_regionprice_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionprice',
            old_name='volume',
            new_name='buy_volume',
        ),
        migrations.AddField(
            model_name='regionprice',
            name='sell_volume',
            field=models.IntegerField(default=0),
        ),
    ]
