# Generated by Django 3.0.8 on 2020-07-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20200725_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionprice',
            name='buy_volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='regionprice',
            name='sell_volume',
            field=models.BigIntegerField(default=0),
        ),
    ]
