# Generated by Django 3.0.8 on 2020-07-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0003_auto_20200725_0141'),
        ('pricing', '0004_auto_20200725_0445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regionprice',
            unique_together={('region', 'type')},
        ),
    ]
