version: "3"
services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    command: ./manage.py runserver 0:${PORT}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12.3
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}

  redis:
    image: redis:5.0
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
