version: "3"
services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
      - redis

  celery:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    command: celery worker -A jita -B -c ${CELERY_WORKERS} -l info
      --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:5.0
    volumes:
      - redisdata:/data

volumes:
  redisdata:
