# Generated by Django 3.0.8 on 2020-07-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='type',
            name='sell',
        ),
        migrations.AddField(
            model_name='type',
            name='highest_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='type',
            name='highest_sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='type',
            name='lowest_buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='type',
            name='lowest_sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
